// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PJT_ERP.QC.Api.Infrastructure.Persistence;

#nullable disable

namespace PJT_ERP.QC.Api.Migrations
{
    [DbContext(typeof(QcContext))]
    partial class QcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PJT_ERP.QC.Api.Domain.Entities.QcInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedReviewerName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("assigned_reviewer_name");

                    b.Property<Guid?>("AssignedReviewerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_reviewer_user_id");

                    b.Property<string>("BarcodeUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("barcode_uid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerDrawingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("customer_drawing_url");

                    b.Property<string>("Decision")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("decision");

                    b.Property<string>("DesignReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("design_reference");

                    b.Property<string>("DrawingRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("drawing_ref");

                    b.Property<string>("MaterialSpec")
                        .HasColumnType("text")
                        .HasColumnName("material_spec");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("OrderQty")
                        .HasColumnType("integer")
                        .HasColumnName("order_qty");

                    b.Property<string>("PorNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("por_number");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<DateTime?>("ProductionFinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("production_finished_at_utc");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.PrimitiveCollection<List<string>>("ProductionPhotos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("production_photos");

                    b.PrimitiveCollection<List<string>>("QcPhotos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("qc_photos");

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ref_no");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("reviewer_name");

                    b.Property<string>("SpkNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("spk_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId")
                        .IsUnique();

                    b.HasIndex("RefNo")
                        .IsUnique();

                    b.ToTable("qc_inspections", (string)null);
                });

            modelBuilder.Entity("PJT_ERP.Shared.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
