name: Trivy Security Scan

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"
  pull_request:
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scanner
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
